#!/usr/bin/env bash
# Bash script that will display information about subdomains

if [ "$#" -eq 2 ]
then
	type=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s",$4;} END {print ""}')
	dest=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s",$5;} END {print ""}')
	subd=$2
	echo "The subdomain $subd is a $type record and points to $dest"
else
	for i in www lb-01 web-01 web-02
	do
		typ=$(dig $i."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s",$4;} END {print ""}')
		destin=$(dig $i."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf "%s",$5;} END {print ""}')
		echo "The subdomain $i is a $typ record and points to $destin"
	done
fi