#!/usr/bin/env bash
# Install nginx on your web-02 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '23 a add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
