#!/usr/bin/env bash
# Find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sudo su
service nginx start
echo "server {                                                                                        
       listen 80 default_server;                                                                      
       listen [::]:80 default_server;                                                                 
       }" >> /etc/nginx/nginx.conf
service nginx reload
