#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100.

var=1

while [ "$var" -lt "101" ]
do 
if [ $((var%3)) -eq 0 ] && [ $((var%5)) -eq 0 ]
then
	echo "FizzBuzz"
elif [ $((var%3)) -eq 0 ]
then
	echo "Fizz"
elif [ $((var%5)) -eq 0 ]
then
	echo "Buzz"
else [ "$var" -lt "101" ]
	echo "$var"
fi

var=$((var+1)) 

done

exit 0