#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes

hour=0

while [ "$hour" -lt 13 ]
do 
echo "Hour: $hour"
hour=$((hour+1)) 

min=1
while [ "$min" -lt 60 ]
	do
	echo $min
	min=$((min+1))
	done
done

exit 0