#!/usr/bin/env bash                                                                          
# Run software as another user
name=$1                                                                                                      
sudo -u "$name" 'whoami'                                                                            
