#!/usr/bin/env bash                                                                          
# Run Nginx as Nginx

sudo pkill apache2
sudo chmod 744 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
